import Head from 'next/head'
import Mrc20Presale from '../src/components/Mrc20Presale'

export default function Home() {
  return (
    <>
      <Head>
        <title>Muon MRC20 Presale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mrc20Presale />
    </>
  )
}
